In [ ]:
print("hi")

hi

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
data =[1,2,3,4,5]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s=pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s=pd.Series(data=[1,2,3,4,5],index=["a","b","c","d","e"])

In [ ]:
s=pd.Series(data=[1,2,3,4,5]),index=(["a","b","c","d","e"])

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (225397047.py, line 1)

In [ ]:
s=pd.Series(data=[1,2,3,4,5],index=["a","b","c,","d","e"])
print(s)

a     1
b     2
c,    3
d     4
e     5
dtype: int64

In [ ]:
#with dict
s2 = pd.Series({'x' : 100, 'y' : 200, 'z' : 300})
print(s2)

x    100
y    200
z    300
dtype: int64

In [ ]:
#accessing
import pandas as pd
data = ['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser = pd.Series(data)
print(ser[:6])

0    g
1    e
2    e
3    k
4    s
5    f
dtype: object

In [ ]:
import pandas as pd
data = ['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser = pd.Series(data)
print(ser[:2])

0    g
1    e
dtype: object

In [ ]:
import pandas as pd
data = ['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser = pd.Series(data)
print(ser[:4])

0    g
1    e
2    e
3    k
dtype: object

In [ ]:
import pandas as pd
data = ['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser = pd.Series(data)
print(ser[:-4])

0    g
1    e
2    e
3    k
4    s
5    f
6    o
7    r
8    g
dtype: object

In [ ]:
import pandas as pd
data = ['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser = pd.Series(data)
print(ser[-2:])

11    k
12    s
dtype: object

In [ ]:
#updating
s1 = pd.Series([10,20,30,40], index=['a','b','c','d'])
print(s1)
s1['a'] = 99
print(s1)

a    10
b    20
c    30
d    40
dtype: int64
a    99
b    20
c    30
d    40
dtype: int64

In [ ]:
s1 = pd.Series([10,20,30,40], index=['a','b','c','d'])
print(s1)
s1['b'] = 50
print(s1)

a    10
b    20
c    30
d    40
dtype: int64
a    10
b    50
c    30
d    40
dtype: int64

In [ ]:
s1['c'] = 70
print(s1)

a    10
b    50
c    70
d    40
dtype: int64

In [ ]:
#adding the element
s1['e'] = 50
print(s1)

a    10
b    50
c    70
d    40
e    50
dtype: int64

In [ ]:
#delete the element
s1 = s1.drop('b')
print(s1)

a    10
c    70
d    40
e    50
dtype: int64

In [ ]:
#permanently deletes
ser=ser.drop(5)
print(ser)

0     g
1     e
2     e
3     k
4     s
6     o
7     r
8     g
9     e
10    e
11    k
12    s
dtype: object

In [ ]:
import pandas as pd
StudentID = [101, 102, 103, 104, 105]
Marks = [78, 85, 92, 67, 88]
s = pd.Series(Marks,index=StudentID)
print(s)

101    78
102    85
103    92
104    67
105    88
dtype: int64

In [ ]:
s[104] = 75
print(s)

0      101
1      102
2      103
3      104
4      105
104     75
dtype: int64

In [ ]:
import pandas as pd
empID = [1001, 1002, 1003, 1004, 1005]
salary = [35000, 42000, 30000, 50000, 45000]
ser = pd.Series(salary,index=empID)
print(ser)

1001    35000
1002    42000
1003    30000
1004    50000
1005    45000
dtype: int64

In [ ]:
ser[1003]=40000

In [ ]:
ser=ser.drop(1002)

In [ ]:
ser[1006]=55000

In [ ]:
print(ser[:3])

1001    35000
1003    40000
1004    50000
dtype: int64

In [ ]:
import pandas as pd
StudentID = [101, 102, 103, 104, 105]
Marks = [78, 85, 92, 67, 88]
s = pd.Series(Marks,index=StudentID)
print(s)

101    78
102    85
103    92
104    67
105    88
dtype: int64

In [ ]:
print("Marks of Student 103:")
print(s[103])

Marks of Student 103:
92

In [ ]:
s[104] = 75
print(s)

101    78
103    92
104    75
105    88
106    90
dtype: int64

In [ ]:
s[106] = 90
print(s)

101    78
103    92
104    75
105    88
106    90
dtype: int64

In [ ]:
import pandas as pd
empID = [1001, 1002, 1003, 1004, 1005]
salary = [35000, 42000, 30000, 50000, 45000]
ser = pd.Series(salary,index=empID)
print(ser)

1001    35000
1002    42000
1003    30000
1004    50000
1005    45000
dtype: int64

In [ ]:
ser[1003] = 40000
print(ser)

1001    35000
1002    42000
1003    40000
1004    50000
1005    45000
dtype: int64

In [ ]:
ser[1006] = 55000
print(ser)

1001    35000
1003    40000
1004    50000
1005    45000
1006    55000
dtype: int64

In [ ]:
print("First 3 employees:")
print(ser.head(3))

First 3 employees:
1001    35000
1003    40000
1004    50000
dtype: int64

In [ ]:
import pandas as pd
ProductID = ['P101', 'P102', 'P103', 'P104', 'P105']
Price = [500, 750, 1200, 900, 1500]
s3 = pd.Series(Price,index=ProductID)
print(s3)

P101     500
P102     750
P103    1200
P104     900
P105    1500
dtype: int64

In [ ]:
print("Price of P103:")
print(s3['P103'])

Price of P103:
1200

In [ ]:
s3['P102']=800
print(s3)

P101     500
P102     800
P103    1200
P105    1500
P106    2000
dtype: int64

In [ ]:
s3 = s3.drop('P104')

In [ ]:
s3['P106']=2000
print(s3)

P101     500
P102     800
P103    1200
P105    1500
P106    2000
dtype: int64

In [ ]:
import pandas as pd
AccountID = ['A101', 'A102', 'A103', 'A104', 'A105']
Balance = [25000, 45000, 32000, 18000, 60000]
s4 = pd.Series(Balance,index=AccountID)
print(s4)

A101    25000
A102    45000
A103    32000
A104    18000
A105    60000
dtype: int64

In [ ]:
print('Balance account of A103')
print(s4['A103'])

Balance account of A103
32000

In [ ]:
s4['A104']=25000
print(s4)

A102    45000
A103    32000
A104    25000
A105    60000
A106    40000
dtype: int64

In [ ]:
s4=s4.drop('A101')

In [ ]:
s4['A106']=40000
print(s4)

A102    45000
A103    32000
A104    25000
A105    60000
A106    40000
dtype: int64

In [ ]:
import pandas as pd
Days = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
Temp = [31,32,34,33,35,36,34]
s5 = pd.Series(Temp, index=Days)
print(s5)

monday       31
tuesday      32
wednesday    34
thursday     33
friday       35
saturday     36
sunday       34
dtype: int64

In [ ]:
s5['thursday'] = 32
print(s5)

monday         31
tuesday        32
wednesday      34
thursday       32
friday         35
sunday         34
Thursday       32
Next Monday    30
dtype: int64

In [ ]:
s5 = s5.drop('saturday')

In [ ]:
s5['Next Monday'] = 30

In [ ]:
#DAY - 02 06/10/26
#dataframes creation
#using list
#list
import pandas as pd
data = [
    ["Ravi", 22, 30000],
    ["Priya", 24, 40000],
    ["Arun", 21, 28000]
]

df = pd.DataFrame(data,columns=["Name", "Age", "Salary"])

print(df)

    Name  Age  Salary
0   Ravi   22   30000
1  Priya   24   40000
2   Arun   21   28000

In [ ]:
#tuple
data = (("Ravi", 22, 30000),
        ("Priya", 24, 40000),
        ("Arun", 21, 28000)
)

df = pd.DataFrame(data,columns=("Name", "Age", "Salary"))

print(df)

    Name  Age  Salary
0   Ravi   22   30000
1  Priya   24   40000
2   Arun   21   28000

In [ ]:
#dict
data = {
    'Name':['Sami','Hemi','Tuhi'],
    'Age':[23,22,18],
    'City':['Chennai','Vizag','Mumbai']
}

df = pd.DataFrame(data)
print(df)

   Name  Age     City
0  Sami   23  Chennai
1  Hemi   22    Vizag
2  Tuhi   18   Mumbai

In [ ]:
#create a dataframe sales and profit of every month in the first 6 months of the year.
import pandas as pd
data = [
    ['jan',10000, 'mobiles'],
    ['feb',20000,'earpods'],
    ['mar',30000,'mouse'],
    ['apr',40000,'laptop'],
    ['may',50000,'keyboard'],
    ['jun',60000,'wire']
]
df = pd.DataFrame(data,columns=['Month','Profits','Sales'])
print(df)

  Month  Profits     Sales
0   jan    10000   mobiles
1   feb    20000   earpods
2   mar    30000     mouse
3   apr    40000    laptop
4   may    50000  keyboard
5   jun    60000      wire

In [ ]:
#create dataframe with set
my_set = {100, 200, 300, 400}

df = pd.DataFrame(list(my_set),columns=['Values'])
print(df)

   Values
0     200
1     100
2     400
3     300

In [ ]:
#converting single series into dataframe
s = pd.Series(
    [1,2,3,4],
    name='Numbers')
df = s.to_frame()
df.columns=["digits"] #renaming the columns
print(df)

   digits
0       1
1       2
2       3
3       4

In [ ]:
#converting multiple series into dataframe
s2=pd.Series([10,11,12,13,14])
s3=pd.Series([21,22,23,24,25])
d= {
"marks-A" :s,
"marks-B" :s2,
"marks-C" :s3}
df = pd.DataFrame(d)
df.columns=["Sanskrit","Social","Hindi"] #renaming the column names
print(df)

   Sanskrit  Social  Hindi
0       1.0      10     21
1       2.0      11     22
2       3.0      12     23
3       4.0      13     24
4       NaN      14     25

In [ ]:
#renaming the column names
df=pd.DataFrame([
    [1, 2],
    [3, 4]])
df.columns = ['A','B']
print(df)

   A  B
0  1  2
1  3  4

In [ ]:
#renaming the column name permanently using df.rename and inplace=True
df.rename(columns={'A': 'Alpha','B': 'Beta'},inplace=True)
print(df)

   Alpha  Beta
0      1     2
1      3     4

In [ ]:
s2=pd.Series([10,11,12,13,14,15,16,17,18,19])
s3=pd.Series([21,22,23,24,25,26,27,28,29,30])
d= {
#"marks-A" :s,
"marks-B" :s2,
"marks-C" :s3}
df = pd.DataFrame(d)
df.columns=["Sanskrit","Social"] #renaming the column names
print(df)
#viewing
print(df.head()) #top 5 method
print(df.tail()) #bottom 5 method
print(len(df)) #no. of rows method
print(df.shape) #no.of rows and columns (attribute)
df.index #(attribute)
df.values #entire data (attribute)

   Sanskrit  Social
0        10      21
1        11      22
2        12      23
3        13      24
4        14      25
5        15      26
6        16      27
7        17      28
8        18      29
9        19      30
   Sanskrit  Social
0        10      21
1        11      22
2        12      23
3        13      24
4        14      25
   Sanskrit  Social
5        15      26
6        16      27
7        17      28
8        18      29
9        19      30
10
(10, 2)

array([[10, 21],
       [11, 22],
       [12, 23],
       [13, 24],
       [14, 25],
       [15, 26],
       [16, 27],
       [17, 28],
       [18, 29],
       [19, 30]])

In [ ]:
import pandas as pd
data = ['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser = pd.Series(data)
print(ser[-2:])
print(len(df)) #no. of elements

11    k
12    s
dtype: object
10

In [ ]:
import pandas as pd
employees = [
    ['Sami',23,'Chennai',50000],
    ['Hemi',22,'Mumbai',60000],
    ['Tuhi',18,'Ooty',40000],
    ['Chaaha',15,'Pondicherry',30000],
    ['Keshvi',13,'Kerala',20000]
]
df = pd.DataFrame(employees,columns=['Name','Age','City','Salary'])
print(df)

     Name  Age         City  Salary
0    Sami   23      Chennai   50000
1    Hemi   22       Mumbai   60000
2    Tuhi   18         Ooty   40000
3  Chaaha   15  Pondicherry   30000
4  Keshvi   13       Kerala   20000

In [ ]:
import pandas as pd
Sales = {
    'Products':['mobiles','earphones','keyboards'],
    'Category':['gaming','wired','connection type'],
    'Price':[100000,200000,150000],
    'Quantity':[10,9,8]
}
df = pd.DataFrame(Sales)
print(df)

    Products         Category   Price  Quantity
0    mobiles           gaming  100000        10
1  earphones            wired  200000         9
2  keyboards  connection type  150000         8

In [ ]:
import pandas as pd
students = {
    'Student_Id':[101,102,103,104,105],
    'Name':['Sami','Hemi','Tuhi','Chaaha','Keshvi'],
    'Course':['DA','Py','SQL','PBI','Excel'],
    'Marks':[77,76,75,74,73]
}
df=pd.DataFrame(students)
print(df)

   Student_Id    Name Course  Marks
0         101    Sami     DA     77
1         102    Hemi     Py     76
2         103    Tuhi    SQL     75
3         104  Chaaha    PBI     74
4         105  Keshvi  Excel     73

In [ ]:
import pandas as pd
Company = (
    (101,'HR',3),
    (102,'PM',2),
    (103,'QA',1),
    (104,'IT',4),
    (105,'Non-IT',5)
)
df = pd.DataFrame(Company,columns=("Employee_Id", "Department", "Experience"))
print(df)

   Employee_Id Department  Experience
0          101         HR           3
1          102         PM           2
2          103         QA           1
3          104         IT           4
4          105     Non-IT           5

In [ ]:
import pandas as pd
#create separate series
name = pd.Series(["Sami","Hemi","Tuhi","Chaaha","Keshvi"])
age = pd.Series([23,22,18,12,10])
city = pd.Series(["Chn","Mum","Bnglr","Vzg","Pondy"])
#combine Series into a DataFrame
df = pd.DataFrame({
    "Name":name,
    "Age":age,
    "City":city
})
#Display the DataFrame
print(df)

     Name  Age   City
0    Sami   23    Chn
1    Hemi   22    Mum
2    Tuhi   18  Bnglr
3  Chaaha   12    Vzg
4  Keshvi   10  Pondy

In [ ]:
#Day 3 07/10/26

In [ ]:
import pandas as pd
data = {
    "Name":["Ravi","Priya","Arun","Sneha",'Kiran',"Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyd","Chn","Bnglr","Hyd","Mum","Chn","Bnglr","Mum"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]}

df = pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

     Name  Age   City  Salary
0    Ravi   22    Hyd   30000
1   Priya   24    Chn   40000
2    Arun   21  Bnglr   28000
3   Sneha   25    Hyd   50000
4   Kiran   23    Mum   35000
5  Anjali   26    Chn   45000
6  Vikram   20  Bnglr   25000
7   Meena   27    Mum   55000

In [ ]:
#Viewing and Selecting
print(df.head())
print("__________________________________________________________________")
print(df.tail())
print("__________________________________________________________________")
print(df.info())
print("__________________________________________________________________")
print(df.describe())
print("__________________________________________________________________")
print(len(df))
print("__________________________________________________________________")
print(df.shape)
print("__________________________________________________________________")
print(df.index)
print("__________________________________________________________________")
print(df)

    Name  Age   City  Salary
0   Ravi   22    Hyd   30000
1  Priya   24    Chn   40000
2   Arun   21  Bnglr   28000
3  Sneha   25    Hyd   50000
4  Kiran   23    Mum   35000
__________________________________________________________________
     Name  Age   City  Salary
3   Sneha   25    Hyd   50000
4   Kiran   23    Mum   35000
5  Anjali   26    Chn   45000
6  Vikram   20  Bnglr   25000
7   Meena   27    Mum   55000
__________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      int64
 2   City    8 non-null      object
 3   Salary  8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes
None
__________________________________________________________________
            Age        Salary
count   8.00000      8.000000
mean   23.50000  38500.000000
std     2.44949  10862.780491
min    20.00000  25000.000000
25%    21.75000  29500.000000
50%    23.50000  37500.000000
75%    25.25000  46250.000000
max    27.00000  55000.000000
__________________________________________________________________
8
__________________________________________________________________
(8, 4)
__________________________________________________________________
RangeIndex(start=0, stop=8, step=1)
__________________________________________________________________
     Name  Age   City  Salary
0    Ravi   22    Hyd   30000
1   Priya   24    Chn   40000
2    Arun   21  Bnglr   28000
3   Sneha   25    Hyd   50000
4   Kiran   23    Mum   35000
5  Anjali   26    Chn   45000
6  Vikram   20  Bnglr   25000
7   Meena   27    Mum   55000

In [ ]:
import pandas as pd

data = {
    "Name":["Ravi","Priya","Arun","Sneha",'Kiran',"Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyd","Chn","Bnglr","Hyd","Mum","Chn","Bnglr","Mum"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]
}

df = pd.DataFrame(data)
print(df[["Name","Age"]])

     Name  Age
0    Ravi   22
1   Priya   24
2    Arun   21
3   Sneha   25
4   Kiran   23
5  Anjali   26
6  Vikram   20
7   Meena   27

In [ ]:
print(df[["Name","Age","City","Salary"]])

     Name  Age   City  Salary
0    Ravi   22    Hyd   30000
1   Priya   24    Chn   40000
2    Arun   21  Bnglr   28000
3   Sneha   25    Hyd   50000
4   Kiran   23    Mum   35000
5  Anjali   26    Chn   45000
6  Vikram   20  Bnglr   25000
7   Meena   27    Mum   55000

In [ ]:
print(df[0:3])

    Name  Age   City  Salary
0   Ravi   22    Hyd   30000
1  Priya   24    Chn   40000
2   Arun   21  Bnglr   28000

In [ ]:
df.loc[103:105]

Empty DataFrame
Columns: [Name, Age, City, Salary]
Index: []

In [ ]:
df["Salary"]>45000 #boolean values

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7     True
Name: Salary, dtype: bool

In [ ]:
df[df["Salary"]<35000]

     Name  Age   City  Salary
0    Ravi   22    Hyd   30000
2    Arun   21  Bnglr   28000
6  Vikram   20  Bnglr   25000

In [ ]:
import pandas as pd

data = {
    "Student_ID":[101,102,103,104,105,106,107,108,109,110],
    "Name":["Aarav","Priya","Rahul","Sneha","Arjun",
            "Divya","Kiran","Ananya","Rohit","Meena"],
    "Age":[20,21,19,22,20,21,23,19,22,20],
    "Course":["Python","Power BI","Python","Excel","Python",
              "Power Bi","Excel","Python","Power BI","Excel"],
    "Marks":[85,78,92,67,88,74,81,95,69,90],
    "Attendance":[92,85,96,78,89,82,91,98,75,94],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Pune",
            "Chennai","Hyderabad","Bangalore","Pune","Hyderabad"]}
df = pd.DataFrame(data)
print(df)

   Student_ID    Name  Age    Course  Marks  Attendance       City
0         101   Aarav   20    Python     85          92  Hyderabad
1         102   Priya   21  Power BI     78          85    Chennai
2         103   Rahul   19    Python     92          96  Bangalore
3         104   Sneha   22     Excel     67          78  Hyderabad
4         105   Arjun   20    Python     88          89       Pune
5         106   Divya   21  Power Bi     74          82    Chennai
6         107   Kiran   23     Excel     81          91  Hyderabad
7         108  Ananya   19    Python     95          98  Bangalore
8         109   Rohit   22  Power BI     69          75       Pune
9         110   Meena   20     Excel     90          94  Hyderabad

In [ ]:
df = pd.DataFrame(data)
print(df)

   Student_ID    Name  Age    Course  Marks  Attendance       City
0         101   Aarav   20    Python     85          92  Hyderabad
1         102   Priya   21  Power BI     78          85    Chennai
2         103   Rahul   19    Python     92          96  Bangalore
3         104   Sneha   22     Excel     67          78  Hyderabad
4         105   Arjun   20    Python     88          89       Pune
5         106   Divya   21  Power Bi     74          82    Chennai
6         107   Kiran   23     Excel     81          91  Hyderabad
7         108  Ananya   19    Python     95          98  Bangalore
8         109   Rohit   22  Power BI     69          75       Pune
9         110   Meena   20     Excel     90          94  Hyderabad

In [ ]:
print(df.head())

   Student_ID   Name  Age    Course  Marks  Attendance       City
0         101  Aarav   20    Python     85          92  Hyderabad
1         102  Priya   21  Power BI     78          85    Chennai
2         103  Rahul   19    Python     92          96  Bangalore
3         104  Sneha   22     Excel     67          78  Hyderabad
4         105  Arjun   20    Python     88          89       Pune

In [ ]:
print(df.tail(3))

   Student_ID    Name  Age    Course  Marks  Attendance       City
7         108  Ananya   19    Python     95          98  Bangalore
8         109   Rohit   22  Power BI     69          75       Pune
9         110   Meena   20     Excel     90          94  Hyderabad

In [ ]:
print(df.info)

<bound method DataFrame.info of    Student_ID    Name  Age    Course  Marks  Attendance       City
0         101   Aarav   20    Python     85          92  Hyderabad
1         102   Priya   21  Power BI     78          85    Chennai
2         103   Rahul   19    Python     92          96  Bangalore
3         104   Sneha   22     Excel     67          78  Hyderabad
4         105   Arjun   20    Python     88          89       Pune
5         106   Divya   21  Power Bi     74          82    Chennai
6         107   Kiran   23     Excel     81          91  Hyderabad
7         108  Ananya   19    Python     95          98  Bangalore
8         109   Rohit   22  Power BI     69          75       Pune
9         110   Meena   20     Excel     90          94  Hyderabad>

In [ ]:
print(df["Name"])

0     Aarav
1     Priya
2     Rahul
3     Sneha
4     Arjun
5     Divya
6     Kiran
7    Ananya
8     Rohit
9     Meena
Name: Name, dtype: object

In [ ]:
print(df[["Name","Course","Marks"]])

     Name    Course  Marks
0   Aarav    Python     85
1   Priya  Power BI     78
2   Rahul    Python     92
3   Sneha     Excel     67
4   Arjun    Python     88
5   Divya  Power Bi     74
6   Kiran     Excel     81
7  Ananya    Python     95
8   Rohit  Power BI     69
9   Meena     Excel     90

In [ ]:
df[["Student_ID","Attendance","City"]].loc[0:9]

   Student_ID  Attendance       City
0         101          92  Hyderabad
1         102          85    Chennai
2         103          96  Bangalore
3         104          78  Hyderabad
4         105          89       Pune
5         106          82    Chennai
6         107          91  Hyderabad
7         108          98  Bangalore
8         109          75       Pune
9         110          94  Hyderabad

In [ ]:
df[["Student_ID"]].loc[103:107]

Empty DataFrame
Columns: [Student_ID]
Index: []

In [ ]:
df[["Name","Course","Marks"]].loc[1:5]

    Name    Course  Marks
1  Priya  Power BI     78
2  Rahul    Python     92
3  Sneha     Excel     67
4  Arjun    Python     88
5  Divya  Power Bi     74

In [ ]:
df[["Name","Marks","City"]].iloc[::107]

    Name  Marks       City
0  Aarav     85  Hyderabad

In [ ]:
df[["Name","Marks","City"]].loc[7]

Name        Ananya
Marks           95
City     Bangalore
Name: 7, dtype: object

In [ ]:
df[["Student_ID","Name","Course","Marks"]].iloc[0:4]

   Student_ID   Name    Course  Marks
0         101  Aarav    Python     85
1         102  Priya  Power BI     78
2         103  Rahul    Python     92
3         104  Sneha     Excel     67

In [ ]:
df[["Name","Course","Marks"]].iloc[2:7]

    Name    Course  Marks
2  Rahul    Python     92
3  Sneha     Excel     67
4  Arjun    Python     88
5  Divya  Power Bi     74
6  Kiran     Excel     81

In [ ]:
df[["Marks","Attendance","City"]].iloc[-3:]

   Marks  Attendance       City
7     95          98  Bangalore
8     69          75       Pune
9     90          94  Hyderabad

In [ ]:
df[df["Marks"]>80]

   Student_ID    Name  Age  Course  Marks  Attendance       City
0         101   Aarav   20  Python     85          92  Hyderabad
2         103   Rahul   19  Python     92          96  Bangalore
4         105   Arjun   20  Python     88          89       Pune
6         107   Kiran   23   Excel     81          91  Hyderabad
7         108  Ananya   19  Python     95          98  Bangalore
9         110   Meena   20   Excel     90          94  Hyderabad

In [ ]:
#Day 5 08/10/26

In [ ]:
#Manipulating Data
import pandas as pd
sales = pd.Series(
    [5000, 7000, None, 9000, 8000, 10000, None],
    index=[
        "Monday","Tuesday","Wednesday","Thursday",
        "Friday","Saturday","Sunday"])
print(sales)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64
5000.0

In [ ]:
#aggregations

#min
print(sales.min())

5000.0

In [ ]:
#max
print(sales.max())

10000.0

In [ ]:
#mean
print(sales.mean())

7800.0

In [ ]:
#sum
print(sales.sum())

39000.0

In [ ]:
#var
print(sales.var())

3700000.0

In [ ]:
#std
print(sales.std())

1923.5384061671346

In [ ]:
print(sales.dtype) #check the datatype

float64

In [ ]:
#updating
sales["Tuesday"]=9500
print(sales)

Monday        5000.0
Tuesday       9500.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

In [ ]:
#adding
sales["jan"]=7800
print(sales)

Monday        5000.0
Tuesday       9500.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
jan           7800.0
dtype: float64

In [ ]:
sales=sales.drop("Tuesday")
print(sales)

KeyError: "['Tuesday'] not found in axis"

In [ ]:
print(sales)

Monday        5000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
jan           7800.0
dtype: float64

In [ ]:
print(sales +2000)

Monday        7000.0
Wednesday        NaN
Thursday     11000.0
Friday       10000.0
Saturday     12000.0
Sunday           NaN
jan           9800.0
dtype: float64

In [ ]:
print(sales *2)

Monday       10000.0
Wednesday        NaN
Thursday     18000.0
Friday       16000.0
Saturday     20000.0
Sunday           NaN
jan          15600.0
dtype: float64

In [ ]:
#combine two series
s=pd.Series([1,2,3,4,5]) #index=[9,7,6,8,0])
s1=pd.Series([101,102,103,104,105])#index=[901,902,903,904,905])
print(s)
print(s1)
d=pd.concat([s,s1]) #wrong index will appear
c=pd.concat([s,s1],ignore_index=True) #correct index values will appear
print(d)
print(c)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    101
1    102
2    103
3    104
4    105
dtype: int64
0      1
1      2
2      3
3      4
4      5
0    101
1    102
2    103
3    104
4    105
dtype: int64
0      1
1      2
2      3
3      4
4      5
5    101
6    102
7    103
8    104
9    105
dtype: int64

In [ ]:
import pandas as pd

data = {
    "Name":["Ravi","Priya","Arun","Sneha",'Kiran',"Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyd","Chn","Bnglr","Hyd","Mum","Chn","Bnglr","Mum"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]
}
df = pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

       Name  Age   City  Salary
101    Ravi   22    Hyd   30000
102   Priya   24    Chn   40000
103    Arun   21  Bnglr   28000
104   Sneha   25    Hyd   50000
105   Kiran   23    Mum   35000
106  Anjali   26    Chn   45000
107  Vikram   20  Bnglr   25000
108   Meena   27    Mum   55000

In [ ]:
print(df["Age"].sum())

188

In [ ]:
print(df["Age"].mean())

23.5

In [ ]:
print(df["Age"].std())

2.449489742783178

In [ ]:
print(df["Age"].count())

8

In [ ]:
print(df["Salary"].sum())

308000

In [ ]:
print(df["Salary"].mean())

38500.0

In [ ]:
print(df["Salary"].std())

10862.780491200216

In [ ]:
print(df["Salary"].count())

8

In [ ]:
print(df["Salary"].min())

25000

In [ ]:
print(df["Salary"].max())

55000

In [ ]:
print(df["Salary"].median())

37500.0

In [ ]:
print(df["Age"].min())

20

In [ ]:
print(df["Age"].max())

27

In [ ]:
print(df["Age"].median())

23.5

In [ ]:
print(df["Age"].var())

6.0

In [ ]:
print(df["Salary"].var())

118000000.0

In [ ]:
df['Bonus'] = df['Salary'] * 0.10
print(df)

       Name  Age   City  Salary   Bonus
101    Ravi   22    Hyd   30000  3000.0
102   Priya   24    Chn   40000  4000.0
103    Arun   21  Bnglr   28000  2800.0
104   Sneha   25    Hyd   50000  5000.0
105   Kiran   23    Mum   35000  3500.0
106  Anjali   26    Chn   45000  4500.0
107  Vikram   20  Bnglr   25000  2500.0
108   Meena   27    Mum   55000  5500.0

In [ ]:
#adding
df["New Salary"] = df["Salary"] + df["Bonus"]
print(df)

       Name  Age   City  Salary   Bonus  New Salary
101    Ravi   23    Hyd   30000  3000.0     33000.0
102   Priya   25    Chn   40000  4000.0     44000.0
103    Arun   22  Bnglr   28000  2800.0     30800.0
104   Sneha   26    Hyd   50000  5000.0     55000.0
105   Kiran   24    Mum   35000  3500.0     38500.0
106  Anjali   27    Chn   45000  4500.0     49500.0
107  Vikram   21  Bnglr   25000  2500.0     27500.0
108   Meena   28    Mum   55000  5500.0     60500.0

In [ ]:
#adding
df["Age"] = df["Age"] + 1
print(df)

       Name  Age   City  Salary   Bonus  New Salary
101    Ravi   23    Hyd   30000  3000.0     33000.0
102   Priya   25    Chn   40000  4000.0     44000.0
103    Arun   22  Bnglr   28000  2800.0     30800.0
104   Sneha   26    Hyd   50000  5000.0     55000.0
105   Kiran   24    Mum   35000  3500.0     38500.0
106  Anjali   27    Chn   45000  4500.0     49500.0
107  Vikram   21  Bnglr   25000  2500.0     27500.0
108   Meena   28    Mum   55000  5500.0     60500.0

In [ ]:
#adding and updating all rows
df["New Salary"] = df["New Salary"] + 500
print(df)

       Name  Age   City  Salary   Bonus  New Salary
101    Ravi   23    Hyd   30000  3000.0     34000.0
102   Priya   25    Chn   40000  4000.0     45000.0
103    Arun   22  Bnglr   28000  2800.0     31800.0
104   Sneha   26    Hyd   50000  5000.0     56000.0
105   Kiran   24    Mum   35000  3500.0     39500.0
106  Anjali   27    Chn   45000  4500.0     50500.0
107  Vikram   21  Bnglr   25000  2500.0     28500.0
108   Meena   28    Mum   55000  5500.0     61500.0

In [ ]:
#updating one row
df.loc[df['Name'] == 'Priya','City'] = 'Pune'
print(df)

       Name  Age   City  Salary   Bonus  New Salary
101    Ravi   23    Hyd   30000  3000.0     34000.0
102   Priya   25   Pune   40000  4000.0     45000.0
103    Arun   22  Bnglr   28000  2800.0     31800.0
104   Sneha   26    Hyd   50000  5000.0     56000.0
105   Kiran   24    Mum   35000  3500.0     39500.0
106  Anjali   27    Chn   45000  4500.0     50500.0
107  Vikram   21  Bnglr   25000  2500.0     28500.0
108   Meena   28    Mum   55000  5500.0     61500.0

In [ ]:
#changing the city
df.loc[df['City'] == 'Bnglr','City'] = 'Hyderabad'
print(df)

       Name  Age       City  Salary   Bonus  New Salary
101    Ravi   23        Hyd   30000  3000.0     34000.0
102   Priya   25       Pune   40000  4000.0     45000.0
103    Arun   22  Hyderabad   28000  2800.0     31800.0
104   Sneha   26        Hyd   50000  5000.0     56000.0
105   Kiran   24        Mum   35000  3500.0     39500.0
106  Anjali   27        Chn   45000  4500.0     50500.0
107  Vikram   21  Hyderabad   25000  2500.0     28500.0
108   Meena   28        Mum   55000  5500.0     61500.0

In [ ]:
df.loc[df['City'] == 'Mum','Salary'] =df['Salary']*1.05
print(df)

       Name  Age   City  Salary
101    Ravi   22    Hyd   30000
102   Priya   24    Chn   40000
103    Arun   21  Bnglr   28000
104   Sneha   25    Hyd   50000
105   Kiran   23    Mum   36750
106  Anjali   26    Chn   45000
107  Vikram   20  Bnglr   25000
108   Meena   27    Mum   57750

In [ ]:
df.loc[df['Salary'] <45000 , 'Salary'] =60000
print(df)

       Name  Age   City  Salary
101    Ravi   22    Hyd   60000
102   Priya   24    Chn   60000
103    Arun   21  Bnglr   60000
104   Sneha   25    Hyd   50000
105   Kiran   23    Mum   60000
106  Anjali   26    Chn   45000
107  Vikram   20  Bnglr   60000
108   Meena   27    Mum   57750

In [ ]:
#Deleting
#df.drop,('column name' axis = 1, inplace = True)

In [ ]:
df.drop('Bonus', axis=1,inplace=True)
print(df)

KeyError: "['Bonus'] not found in axis"

In [ ]:
print(df)

       Name  Age   City  Salary
101    Ravi   22    Hyd   60000
102   Priya   24    Chn   60000
103    Arun   21  Bnglr   60000
104   Sneha   25    Hyd   50000
105   Kiran   23    Mum   60000
106  Anjali   26    Chn   45000
107  Vikram   20  Bnglr   60000
108   Meena   27    Mum   57750

In [ ]:
df.drop(columns="New Salary",inplace=True)
print(df)

KeyError: "['New Salary'] not found in axis"

In [ ]:
print(df)

       Name  Age   City  Salary
101    Ravi   22    Hyd   60000
102   Priya   24    Chn   60000
103    Arun   21  Bnglr   60000
104   Sneha   25    Hyd   50000
105   Kiran   23    Mum   60000
106  Anjali   26    Chn   45000
107  Vikram   20  Bnglr   60000
108   Meena   27    Mum   57750

In [ ]:
df.drop(columns="Salary",inplace=True)
print(df)

       Name  Age   City
101    Ravi   22    Hyd
102   Priya   24    Chn
103    Arun   21  Bnglr
104   Sneha   25    Hyd
105   Kiran   23    Mum
106  Anjali   26    Chn
107  Vikram   20  Bnglr
108   Meena   27    Mum

In [ ]:
#Day 6 09/10/26
#reading a file
#df = pd.read_csv("sales.csv")
#isnull() or isna() for detecting missing values
#Dropna() for removing missing values
#fillna() for filling missing values
#isnull.sum() or isna.sum() for counting missing values
#if we have none value in the dataset NAN will be printed in the output.

In [ ]:
import pandas as pd
df=pd.Series(
    [5000, 7000, None, 9000, 8000, 10000, None],
    index=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
print(df)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

In [ ]:
import pandas as pd
df=pd.DataFrame(
    [5000, 7000, None, 9000, 8000, 10000, None],
    index=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
print(df)

                 0
Monday      5000.0
Tuesday     7000.0
Wednesday      NaN
Thursday    9000.0
Friday      8000.0
Saturday   10000.0
Sunday         NaN

In [ ]:
#Cleaning
#handling missing vales
#df.isna()
#df.isna().sum
#df.dropna()

In [ ]:
df.isna()

               0
Monday     False
Tuesday    False
Wednesday   True
Thursday   False
Friday     False
Saturday   False
Sunday      True

In [ ]:
df.isna().sum()

0    2
dtype: int64

In [ ]:
df.fillna(0)

                 0
Monday      5000.0
Tuesday     7000.0
Wednesday      0.0
Thursday    9000.0
Friday      8000.0
Saturday   10000.0
Sunday         0.0

In [ ]:
df.fillna("no data")

                 0
Monday      5000.0
Tuesday     7000.0
Wednesday  no data
Thursday    9000.0
Friday      8000.0
Saturday   10000.0
Sunday     no data

In [ ]:
df.dropna()

                0
Monday     5000.0
Tuesday    7000.0
Thursday   9000.0
Friday     8000.0
Saturday  10000.0

In [ ]:
import pandas as pd
df=pd.DataFrame(
    [5000, 7000, None, 9000, 8000, 10000, None],
    index=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
print(df)

                 0
Monday      5000.0
Tuesday     7000.0
Wednesday      NaN
Thursday    9000.0
Friday      8000.0
Saturday   10000.0
Sunday         NaN

In [ ]:
import pandas as pd
employees = {
    "EmpID":[101,102,103,104],
    "Name":["Asha",None,"Meena","sai"],
    "Department":["Sales","IT","HR",None],
    "Salary":[45000, 60000,None,89000]
}
I =[901,902,903,904]
df = pd.DataFrame(employees,index = I)
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df.isnull()

     EmpID   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False

In [ ]:
df.isna()

     EmpID   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False

In [ ]:
df.isnull().sum()

EmpID         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df.isna().sum()

EmpID         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df.fillna({
    'Name':'Unknown',
    'Salary':0,
    'Department':0

})

     EmpID     Name Department   Salary
901    101     Asha      Sales  45000.0
902    102  Unknown         IT  60000.0
903    103    Meena         HR      0.0
904    104      sai          0  89000.0

In [ ]:
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df.fillna({
    'Name':'Unknown',
    'Salary':0,
    'Department':0

})
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR  89000.0
904    104    sai       None  89000.0

In [ ]:
df['Salary'].fillna(
    df['Salary'].max())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df['Salary'].fillna(
    df['Salary'].min())

901    45000.0
902    60000.0
903    45000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df['Salary'].fillna(
    df['Salary'].mean())

901    45000.000000
902    60000.000000
903    64666.666667
904    89000.000000
Name: Salary, dtype: float64

In [ ]:
df['Salary'].fillna(
    df['Salary'].var())

901    4.500000e+04
902    6.000000e+04
903    5.003333e+08
904    8.900000e+04
Name: Salary, dtype: float64

In [ ]:
df['Salary'].fillna(
    df['Salary'].std())

901    45000.000000
902    60000.000000
903    22368.132093
904    89000.000000
Name: Salary, dtype: float64

In [ ]:
df['Salary'].fillna(
    df['Salary'].sum())

901     45000.0
902     60000.0
903    194000.0
904     89000.0
Name: Salary, dtype: float64

In [ ]:
import pandas as pd
employees = {
    "EmpID":[101,102,103,104],
    "Name":["Asha",None,"Meena","sai"],
    "Department":["Sales","IT","HR",None],
    "Salary":[45000, 60000,None,89000]
}
I =[901,902,903,904]
df = pd.DataFrame(employees,index = I)
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df.tail(2)

     EmpID   Name Department   Salary
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df.head(2)

     EmpID  Name Department   Salary
901    101  Asha      Sales  45000.0
902    102  None         IT  60000.0

In [ ]:
df[["Name","Salary"]]

      Name   Salary
901   Asha  45000.0
902   None  60000.0
903  Meena      NaN
904    sai  89000.0

In [ ]:
df["Salary"]>50000

901    False
902     True
903    False
904     True
Name: Salary, dtype: bool

In [ ]:
df[df["EmpID"] == 103]

     EmpID   Name Department  Salary
903    103  Meena         HR     NaN

In [ ]:
print(df["Department"] == 'IT')

901    False
902     True
903    False
904    False
Name: Department, dtype: bool

In [ ]:
print(df[df["Name"].isna() | df["Department"].isna()])

Empty DataFrame
Columns: [EmployeeID, Name, Department, Salary]
Index: []

In [ ]:
print(df.isna().sum())

EmployeeID    0
Name          0
Department    0
Salary        1
dtype: int64

In [ ]:
df["Department"] = df["Department"].fillna("Not Assigned")
print(df)

     EmployeeID     Name    Department   Salary
901         101     Asha         Sales  45000.0
902         102  Unknown            IT  60000.0
903         103    Meena            HR      NaN
904         104      sai  Not Assigned  95000.0

In [ ]:
df["Bonus"] = df["Salary"] * 0.10
print(df)

     EmpID   Name Department   Salary   Bonus
901    101   Asha      Sales  45000.0  4500.0
902    102   None         IT  60000.0  6000.0
903    103  Meena         HR      NaN     NaN
904    104    sai       None  89000.0  8900.0

In [ ]:
df.loc[df["Name"].str.lower() == "sai", "Salary"] = 95000
print(df)

     EmpID   Name Department   Salary   Bonus
901    101   Asha      Sales  45000.0  4500.0
902    102   None         IT  60000.0  6000.0
903    103  Meena         HR      NaN     NaN
904    104    sai       None  95000.0  8900.0

In [ ]:
df.rename(columns={"EmpID": "EmployeeID"}, inplace=True)
print(df)

     EmployeeID   Name Department   Salary   Bonus
901         101   Asha      Sales  45000.0  4500.0
902         102   None         IT  60000.0  6000.0
903         103  Meena         HR      NaN     NaN
904         104    sai       None  95000.0  8900.0

In [ ]:
df.drop(columns=["Bonus"], inplace=True)
print(df)

     EmployeeID   Name Department   Salary
901         101   Asha      Sales  45000.0
902         102   None         IT  60000.0
903         103  Meena         HR      NaN
904         104    sai       None  95000.0

In [ ]:
print("Total Salary:", df["Salary"].sum())
print("Average Salary:", df["Salary"].mean())
print("Maximum Salary:", df["Salary"].max())
print("Minimum Salary:", df["Salary"].min())

Total Salary: 200000.0
Average Salary: 66666.66666666667
Maximum Salary: 95000.0
Minimum Salary: 45000.0

In [ ]:
print(df.groupby("Department")["Salary"].sum())
print(df)

Department
HR           0.0
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64
     EmployeeID   Name Department   Salary
901         101   Asha      Sales  45000.0
902         102   None         IT  60000.0
903         103  Meena         HR      NaN
904         104    sai       None  95000.0

In [ ]:
print(
    df.groupby("Department").agg(
        Average_Salary=("Salary", "mean"),
        Employee_Count=("EmployeeID", "count")
    )
)

            Average_Salary  Employee_Count
Department
HR                     NaN               1
IT                 60000.0               1
Sales              45000.0               1

In [ ]:
additional_data = {
    "EmpID": [101, 102, 103, 104],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Vizag"],
    "Experience": [2, 3, 1, 4]
}

df_details = pd.DataFrame(additional_data)
print(df_details)

   EmpID       City  Experience
0    101  Hyderabad           2
1    102    Chennai           3
2    103  Bangalore           1
3    104      Vizag           4

In [1]:
#Day 10 14/10/26
import pandas as pd
employees = {
    "EmpID":[101,102,103,104],
    "Name":["Asha",None,"Meena","sai"],
    "Department":["Sales","IT","HR",None],
    "Salary":[45000, 60000,None,89000]
}
I =[901,902,903,904]
df = pd.DataFrame(employees,index = I)
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [2]:
df.groupby('Department')['Salary'].mean()

Department
HR           NaN
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [3]:
df.groupby('Department')['Salary'].min()

Department
HR           NaN
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [4]:
df.groupby('Department')['Salary'].max()

Department
HR           NaN
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [5]:
df.groupby('Department')['Salary'].sum()

Department
HR           0.0
IT       60000.0
Sales    45000.0
Name: Salary, dtype: float64

In [6]:
df.groupby('Department')['Salary'].std()

Department
HR      NaN
IT      NaN
Sales   NaN
Name: Salary, dtype: float64

In [7]:
df.groupby('Department')['Salary'].var()

Department
HR      NaN
IT      NaN
Sales   NaN
Name: Salary, dtype: float64

In [8]:
df.groupby('Department')['Salary'].agg(['mean','max','min'])

               mean      max      min
Department
HR              NaN      NaN      NaN
IT          60000.0  60000.0  60000.0
Sales       45000.0  45000.0  45000.0

In [9]:
df.groupby('Department').agg({
    'EmpID':['mean','max'],
    'Salary':['sum','count']
})

            EmpID        Salary
             mean  max      sum count
Department
HR          103.0  103      0.0     0
IT          102.0  102  60000.0     1
Sales       101.0  101  45000.0     1

In [11]:
import pandas as pd
data = {
    "Name":["Ravi","Priya","Arun","Sneha",'Kiran',"Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyd","Chn","Bnglr","Hyd","Mum","Chn","Bnglr","Mum"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]}

df = pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

       Name  Age   City  Salary
101    Ravi   22    Hyd   30000
102   Priya   24    Chn   40000
103    Arun   21  Bnglr   28000
104   Sneha   25    Hyd   50000
105   Kiran   23    Mum   35000
106  Anjali   26    Chn   45000
107  Vikram   20  Bnglr   25000
108   Meena   27    Mum   55000

In [12]:
#2
print(df['Name'])

101      Ravi
102     Priya
103      Arun
104     Sneha
105     Kiran
106    Anjali
107    Vikram
108     Meena
Name: Name, dtype: object

In [16]:
#3
print(df[["Name","Salary"]])

       Name  Salary
101    Ravi   30000
102   Priya   40000
103    Arun   28000
104   Sneha   50000
105   Kiran   35000
106  Anjali   45000
107  Vikram   25000
108   Meena   55000

In [18]:
#4
print(df[df["Age"]>23])

       Name  Age City  Salary
102   Priya   24  Chn   40000
104   Sneha   25  Hyd   50000
106  Anjali   26  Chn   45000
108   Meena   27  Mum   55000

In [20]:
#5
print(df[df["Salary"]>40000])

       Name  Age City  Salary
104   Sneha   25  Hyd   50000
106  Anjali   26  Chn   45000
108   Meena   27  Mum   55000

In [30]:
#6
df[df["City"]== "Chn"]

       Name  Age City  Salary
102   Priya   24  Chn   40000
106  Anjali   26  Chn   45000

In [44]:
#7
print(df[(df["Salary"] > 35000) & (df["Age"] > 22)])

       Name  Age City  Salary
102   Priya   24  Chn   40000
104   Sneha   25  Hyd   50000
106  Anjali   26  Chn   45000
108   Meena   27  Mum   55000

In [45]:
#8
print(df[df["City"].isin(["Mum", "Bnglr"])])

       Name  Age   City  Salary
103    Arun   21  Bnglr   28000
105   Kiran   23    Mum   35000
107  Vikram   20  Bnglr   25000
108   Meena   27    Mum   55000

In [46]:
#9
print(df[df["Salary"] > 30000][["Name", "Salary"]])

       Name  Salary
102   Priya   40000
104   Sneha   50000
105   Kiran   35000
106  Anjali   45000
108   Meena   55000

In [47]:
#10
print(df.iloc[1:4])

      Name  Age   City  Salary
102  Priya   24    Chn   40000
103   Arun   21  Bnglr   28000
104  Sneha   25    Hyd   50000